Check if window is valid before matchdelete
dvoytik/hi-my-words.nvim pull request #1
Opened 2023-07-23 17:20 UTC by YuCao16

2023-07-23 21:14 UTC, dvoytik commented
Hi @YuCao16 ,

Thank you for your pull request!
I'm assuming you are fixing some bug. Could you please tell how this bug can be reproduced?

2023-07-23 21:51 UTC, YuCao16 commented
> Hi @YuCao16 ,
> 
> Thank you for your pull request! I'm assuming you are fixing some bug. Could you please tell how this bug can be reproduced?

My bad, my previous pr fix nothing. Here's the situation: If I highlight a word that is currently under the cursor, and then proceed to open a sidebar plugin like 'Symbol Outline', the same word appearing in the sidebar does not get highlighted. Additionally, invoking the `vim.fn.matchdelete` function leads to an error. I hope this clarifies the issue I'm encountering.

2023-07-23 21:52 UTC, YuCao16 commented
There should be better solutions, but this is probably the simplest one.

2023-07-26 21:43 UTC, dvoytik requested changes
If you fix that indention problem, I'd merge.
Thanks.

2023-07-26 21:43 UTC, dvoytik commented on lua/hi-my-words/init.lua
> +    pcall(vim.fn.matchdelete, m_id)
I think an indent (two backspace characters) is missing.

2023-07-27 10:57 UTC, YuCao16 commented
@dvoytik fixed!

2023-07-27 22:17 UTC, dvoytik approved these changes

2023-07-27 22:18 UTC, merged

2023-07-27 22:18 UTC, dvoytik commented
Thanks!